### PR TITLE
Handle `EmptyQueryResponse`

### LINKED ISSUE #488: Empty Query Triggers Precondition Failure
### Describe the issue

An empty query with no query content (e.g. only comments) triggers a precondition failure.

### Vapor version

1.21.5

### Operating system and version

macOS 15

### Swift version

swift-driver version: 1.109.2 Apple Swift version 6.0 (swiftlang-6.0.0.3.300 clang-1600.0.20.10) Target: arm64-apple-macosx15.0

### Steps to reproduce

Add/Run this in `PSQLIntegrationTests.swift`:
```swift
    func testCommentOnlyQueryTriggersPrecondition() {
        let eventLoopGroup = MultiThreadedEventLoopGroup(numberOfThreads: 1)
        defer { XCTAssertNoThrow(try eventLoopGroup.syncShutdownGracefully()) }
        let eventLoop = eventLoopGroup.next()

        var conn: PostgresConnection?
        XCTAssertNoThrow(conn = try PostgresConnection.test(on: eventLoop).wait())
        defer { XCTAssertNoThrow(try conn?.close().wait()) }

        _ = try conn?.query("-- Some comments", logger: .psqlTest).wait()
    }
```

### Outcome

<kbd>
Screenshot 2024-06-19 at 2 52 39 PM
</kbd>

### Additional notes

_No response_

### PR DESCRIPTION
**Pull request by MahdiBM**
resolves #488.

### CODE REVIEW

File: Tests/IntegrationTests/PSQLIntegrationTests.swift [hunk 1]
```diff
@@ -123,6 +123,25 @@ final class IntegrationTests: XCTestCase {
...
+        defer { XCTAssertNoThrow(try conn?.close().wait()) }
+
+        var _result: PostgresQueryResult?
+        XCTAssertNoThrow(_result = try conn?.query("""
+            -- Some comments
+            """, logger: .psqlTest).wait())
+
+        let result = try XCTUnwrap(_result)
+        XCTAssertEqual(result.rows, [])
+        XCTAssertEqual(result.metadata.command, "")
```
Comment (MahdiBM) [inline Tests/IntegrationTests/PSQLIntegrationTests.swift:142]: command tag will be empty. Maybe that API should change in V2 to reflect that a query can have no command tag / metadata at all.

File: Sources/PostgresNIO/PostgresDatabase+Query.swift [hunk 2]
```diff
@@ -73,10 +73,7 @@ public struct PostgresQueryMetadata: Sendable {
 
     init?(string: String) {
         let parts = string.split(separator: " ")
-        guard parts.count >= 1 else {
-            return nil
-        }
-        switch parts[0] {
+        switch parts.first {
```
Comment (MahdiBM) [inline Sources/PostgresNIO/PostgresDatabase+Query.swift:76]: So it also parses empty command tags.

**Comment by MahdiBM** [comment]
Nightly tests failing due to the same unrelated test that caused the same issue in #497.

**Review by fabianfett — COMMENTED** [review]
First round

File: Sources/PostgresNIO/New/PSQLRowStream.swift [hunk 3]
```diff
@@ -35,6 +38,7 @@ final class PSQLRowStream: @unchecked Sendable {
         case iteratingRows(onRow: (PostgresRow) throws -> (), EventLoopPromise<Void>, PSQLRowsDataSource)
         case waitingForAll([PostgresRow], EventLoopPromise<[PostgresRow]>, PSQLRowsDataSource)
         case consumed(Result<String, Error>)
+        case finished
```
[the remark this answers is not in the document]
Comment (MahdiBM) [reply Sources/PostgresNIO/New/PSQLRowStream.swift:41]: Right.

[the remark this answers is not in the document]
Comment (fabianfett) [reply Sources/PostgresNIO/New/PSQLRowStream.swift:41]: Can we merge this with `consumed`? And change the `String` to an enum in the consumed case:

```swift
enum Consumed {
    case tag(String)
    case emptyResponse
}
```

File: Sources/PostgresNIO/New/Connection State Machine/ExtendedQueryStateMachine.swift [hunk 4]
```diff
@@ -319,7 +323,23 @@ struct ExtendedQueryStateMachine {
...
     
     mutating func emptyQueryResponseReceived() -> Action {
-        preconditionFailure("Unimplemented")
+        guard case .bindCompleteReceived(let queryContext) = self.state else {
+            return self.setAndFireError(.unexpectedBackendMessage(.emptyQueryResponse))
+        }
+
+        switch queryContext.query {
+        case .unnamed(_, let eventLoopPromise),
+                .executeStatement(_, let eventLoopPromise):
```
Comment (fabianfett) [inline Sources/PostgresNIO/New/Connection State Machine/ExtendedQueryStateMachine.swift:332]:
```suggestion
            .executeStatement(_, let eventLoopPromise):
```

Comment (MahdiBM) [reply Sources/PostgresNIO/New/Connection State Machine/ExtendedQueryStateMachine.swift:332]: Hmm i agree what you mentioned is better, but what is in the PR is what Xcode indents the line to be.
Do you want to go against that?

File: Tests/IntegrationTests/PSQLIntegrationTests.swift (hunk 1 above)
Comment (MahdiBM) [reply Tests/IntegrationTests/PSQLIntegrationTests.swift:142]: https://github.com/vapor/postgres-nio/issues/502

File: Sources/PostgresNIO/New/PSQLRowStream.swift [hunk 5]
```diff
@@ -27,14 +29,20 @@ final class PSQLRowStream: @unchecked Sendable {
     private enum BufferState {
         case streaming(buffer: CircularBuffer<DataRow>, dataSource: PSQLRowsDataSource)
         case finished(buffer: CircularBuffer<DataRow>, commandTag: String)
+        case empty
```
Comment (fabianfett) [inline Sources/PostgresNIO/New/PSQLRowStream.swift:32]: we should combine those two as well. Rename `Consumed` to `StatementSummary`? Use statementSummary instead of commandTag in finished state.

**Review by fabianfett — APPROVED** [review]
LGTM. Great fix!
